name: remove roboshop infrastructure
on: [workflow_dispatch]
jobs:

  DEV:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: terraform destroy
        run: terraform destroy -var-file=env-dev/main.tfvars -auto-approve

  PROD:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-prod/state.tfvars
      - name: terraform destroy
        run: terraform destroy -var-file=env-prod/main.tfvars -auto-approve